### ISSUE TITLE
Can't inflate NewsFragment in mentioned case 

### ISSUE THREAD

**Issue by rakshitsoni02** [TakeoffAndroid/InstaLikeFragmentTransaction#2]
After sample starts:

1. Select NewsFragment (showing properly)
2. Press back(coming back to home)
3. Press NewsFragment again(not working)

**Comment by AVINASH21AK** [comment]
same issue i am also having...

**Comment by rakshitsoni02** [comment]
use BottomNavigationView instead of TabLayout you can customize it's behaviour it will solve the problem, DM if u need the code.

**Comment by AVINASH21AK** [comment]
does stack is manage similar to this demo (InstaLikeFragmentTransaction) ...?
if yes, plz could you send me demo.

**Comment by rakshitsoni02** [comment]
https://gitlab.com/snippets/1713014
try this
